### PR TITLE
Fixed all tests

### PR DESCRIPTION
**Pull request by lluuaapp**
- added Jenkinsfile
- added Travis CI file

### CODE REVIEW

**Comment by rafiki270** [comment]
I don’t think the tests are being launched at all?! :(

**Comment by lluuaapp** [comment]
Travis-Ci seems to be much simpler to use. Can you help me with the Jenkinsfile? How can I install vapor? Brew seems to be no option? Any other way? Ir can I switch to Linux with docker somehow?

**Comment by rafiki270** [comment]
where do I find the travis build succeeding?

**Comment by lluuaapp** [comment]
You can see the tests [here](https://travis-ci.com/lluuaapp/S3).

**Pull request merged**
